create table USERS_TB(
ID_USER bigint(50) NOT NULL AUTO_INCREMENT,
NAME   varchar(60) NOT NULL,
EMAIL varchar(60) NOT NULL,
USER_NAME varchar(60) NOT NULL,
PASSWORD varchar(100) NOT NULL,
CPF    varchar(100) NOT NULL,
DT_REGISTER  TIMESTAMP,
DT_UPDATE  TIMESTAMP,
PRIMARY KEY (`ID_USER`));

